POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Nguyen Van A with billing",
  "email": "sophia.clark_billinga212a2@example.com",
  "address": "Ho Chi Minh City",
  "dateOfBirth": "1995-08-20T00:00:00Z",
  "registeredDate": "2026-04-07T10:30:00Z"
}